FROM golang:alpine


RUN apk add --no-cache git


RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

EXPOSE 8080

CMD ["air", "-build.cmd", "go build -buildvcs=false -o tmp/main ./cmd/api", "-build.bin", "tmp/main"]
